Repository PLUS-POSTECH/soma, pull requests merged in 2019-01, with the labels that each got.

#27 Fix wrong template file
  templates/binary/Dockerfile
Labels: bug

#34 Repository backend
  src/bin/soma/commands/list.rs
  src/data_dir.rs
  src/repo.rs
  src/template.rs
  templates/binary/Dockerfile
  templates/binary/start.sh
Labels: refactoring

#55 Repo add another name
  src/bin/soma/commands/add.rs
  src/ops.rs
  tests/add.rs
  tests/fetch.rs
Labels: new feature

#57 Test run command
  azure-pipelines.yml
  src/bin/soma/commands/run.rs
  src/docker.rs
  src/ops.rs
  tests/common/mod.rs
  tests/run.rs
Labels: enhancement

#63 Implement initial port binding support
  README.md
  src/bin/soma/commands/run.rs
  src/docker.rs
  src/ops.rs
  templates/binary/Dockerfile
  templates/binary/start.sh
  tests/run.rs
Labels: new feature

#67 Build command
  README.md
  src/bin/soma/commands.rs
  src/bin/soma/commands/build.rs
  src/bin/soma/commands/list.rs
  src/bin/soma/commands/run.rs
  src/bin/soma/main.rs
  src/data_dir.rs
  src/ops.rs
  src/repo.rs
  src/repo/backend.rs
  templates/binary/Dockerfile
  tests/add.rs
  tests/common/mod.rs
  tests/fetch.rs
  tests/run.rs
Labels: refactoring

#73 Refactor repository
  src/bin/soma/commands.rs
  src/bin/soma/commands/add.rs
  src/bin/soma/commands/build.rs
  src/bin/soma/commands/fetch.rs
  src/bin/soma/commands/list.rs
  src/bin/soma/commands/remove.rs
  src/bin/soma/commands/run.rs
  src/bin/soma/main.rs
  src/data_dir.rs
  src/docker.rs
  src/error.rs
  src/lib.rs
  src/ops.rs
  src/prelude.rs
  src/repo.rs
  src/repo/backend.rs
  src/repo/repo_manager.rs
  src/template.rs
  tests/add_remove.rs
  tests/common/mod.rs
  tests/fetch.rs
  tests/location_to_backend.rs
  tests/run.rs
Labels: refactoring

#77 Clean stop command
  src/bin/soma/commands.rs
  src/bin/soma/commands/clean.rs
  src/bin/soma/commands/stop.rs
  src/bin/soma/main.rs
  src/docker.rs
  src/error.rs
  src/ops.rs
  templates/binary/Dockerfile
  tests/build_clean.rs
  tests/run_stop.rs
Labels: new feature

#85 Update docker ops
  Cargo.lock
  Cargo.toml
  src/bin/soma/commands/build.rs
  src/docker.rs
  src/error.rs
  src/ops.rs
  tests/build_clean.rs
  tests/run_stop.rs
Labels: dependency, enhancement

#90 Print docker image build status message
  src/docker.rs
  src/error.rs
  src/ops.rs
Labels: ux/ui

#94 Refactor FileEntry
  Cargo.lock
  Cargo.toml
  README.md
  src/data_dir.rs
  src/ops.rs
  src/repo.rs
  src/template.rs
  templates/binary/Dockerfile
  templates/binary/start.sh
  tests/add_remove.rs
  tests/fetch.rs
Labels: dependency, refactoring, ux/ui

#96 Introduce Problem struct to distinguish problems and repositories
  Cargo.lock
  Cargo.toml
  src/bin/soma/commands/build.rs
  src/bin/soma/commands/clean.rs
  src/bin/soma/commands/fetch.rs
  src/bin/soma/commands/list.rs
  src/bin/soma/commands/run.rs
  src/bin/soma/commands/stop.rs
  src/bin/soma/main.rs
  src/docker.rs
  src/error.rs
  src/ops.rs
  src/repo.rs
  src/repo/repo_manager.rs
  src/template.rs
  templates/binary/Dockerfile
  tests/add_remove.rs
  tests/build_clean.rs
  tests/common/mod.rs
  tests/common/test_printer.rs
  tests/run_stop.rs
Labels: new feature, refactoring
