Repository PLUS-POSTECH/soma, pull requests merged in 2019-02, with the labels that each got.

#102 General improvements
  Cargo.lock
  Cargo.toml
  README.md
  azure-pipelines.yml
  hooks/pre-commit
  hooks/pre-push
  src/bin/soma/commands/clean.rs
  src/bin/soma/commands/list.rs
  src/bin/soma/commands/stop.rs
  src/bin/soma/terminal_printer.rs
  src/data_dir.rs
  src/docker.rs
  src/error.rs
  src/lib.rs
  src/ops.rs
  src/problem.rs
  src/problem/configs.rs
  src/problem/configs/binary.rs
  src/problem/configs/common.rs
  src/repo.rs
  src/repository.rs
  src/repository/manager.rs
  src/template.rs
  tests/add_remove.rs
  tests/common/mod.rs
  tests/common/test_printer.rs
  tests/fetch.rs
  tests/location_to_backend.rs
Labels: dependency, enhancement, refactoring

#103 Docker ops refactoring
  .gitattributes
  Cargo.lock
  Cargo.toml
  src/docker.rs
  src/error.rs
  src/ops.rs
  src/problem.rs
  src/problem/configs.rs
  src/problem/configs/binary.rs
  src/problem/configs/common.rs
  src/template.rs
  templates/binary/Dockerfile
  templates/binary/configure_permissions.sh
  templates/binary/start.sh
Labels: enhancement, refactoring

#112 Make Backend a trait
  Cargo.lock
  Cargo.toml
  src/ops.rs
  src/repository.rs
  src/repository/backend.rs
  src/repository/manager.rs
  tests/location_to_backend.rs
Labels: refactoring

#113 Sanitize strings
  Cargo.lock
  Cargo.toml
  src/docker.rs
  src/error.rs
  src/lib.rs
  src/ops.rs
  src/problem.rs
  src/problem/configs/common.rs
  src/repository.rs
  src/repository/backend.rs
  src/repository/manager.rs
  tests/add_remove.rs
Labels: enhancement

#117 Update README
  README.md
Labels: enhancement
